/* PredictIQ Daily Picks — verified fixtures + resilient recent-form scoring. */
(function(){
'use strict';
const state={fixtures:[],picks:[],updatedAt:null,source:null,error:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function todayISO(){const d=new Date();return new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
function formScore(x){if(!x?.rows?.length)return null;const r=x.rows,pts=r.reduce((s,m)=>s+(m.r==='W'?3:m.r==='D'?1:0),0)/(r.length*3),gd=r.reduce((s,m)=>s+(m.gf-m.ga),0)/Math.max(1,r.length);return Math.max(0,Math.min(1,.55*pts+.45*(.5+gd/6)));}
function makePick(f,h,a){const hs=formScore(h),as=formScore(a);if(hs==null||as==null)return {fixture:f,markets:[],confidence:0,missingForm:true};const edge=hs-as,home=Math.max(.05,Math.min(.9,.5+edge*.38+.08)),draw=Math.max(.05,Math.min(.45,.25-Math.abs(edge)*.08)),away=Math.max(.05,1-home-draw),total=hs+as,over25=Math.max(.12,Math.min(.88,.18+total*.55)),btts=Math.max(.12,Math.min(.88,.25+(hs+as)*.42));const markets=[{name:'Home or Draw (1X)',prob:home+draw,why:'Home side has the stronger recent-form signal.'},{name:'Away or Draw (X2)',prob:away+draw,why:'Away side has the stronger recent-form signal.'},{name:'Under 4.5 Goals',prob:1-Math.max(.03,over25*.55),why:'Recent scoring and goal-difference signals do not support an extreme total.'},{name:'Both Teams To Score',prob:btts,why:'Recent attacking output on both sides supports a scoring scenario.'}].filter(m=>m.prob>=.80).sort((a,b)=>b.prob-a.prob).slice(0,3);return {fixture:f,markets,confidence:markets[0]?.prob||0,homeForm:hs,awayForm:as,missingForm:false};}
function fixtureCard(f,p,i){const kickoff=f.kickoff?new Date(f.kickoff):null;const when=kickoff&&!Number.isNaN(kickoff.getTime())?kickoff.toLocaleString():((f.kickoffLocal||'')+' '+(f.timeLocal||'')).trim()||'Time unavailable';const status=String(f.status||'NS').toUpperCase();if(p?.markets?.length)return `<article class="pick-item"><div class="rank">#${i+1}</div><div><h4>${esc(f.home)} vs ${esc(f.away)}</h4><p>${esc(f.competition||'Football')} • ${esc(when)} • ${esc(status)}</p>${p.markets.map(m=>`<p><strong>${esc(m.name)}</strong> — ${(m.prob*100).toFixed(1)}%<br><small>${esc(m.why)}</small></p>`).join('')}<p><span class="pick-label">MODEL QUALIFIED</span> • Recent form: ${p.formMatches||5} matches/team</p></div></article>`;if(p?.error)return `<article class="pick-item"><div class="rank">${i+1}</div><div><h4>${esc(f.home)} vs ${esc(f.away)}</h4><p>${esc(f.competition||'Football')} • ${esc(when)} • ${esc(status)}</p><p><strong>Analysis delayed</strong> — fixture verified, but the free data provider did not return both teams' recent form yet.</p></div></article>`;return `<article class="pick-item"><div class="rank">${i+1}</div><div><h4>${esc(f.home)} vs ${esc(f.away)}</h4><p>${esc(f.competition||'Football')} • ${esc(when)} • ${esc(status)}</p><p><strong>Analysis pending</strong> — fixture verified, but enough recent-form data was not available to produce a qualifying 80% model signal.</p></div></article>`;}
function render(){const host=$('#dailyList')||$('#daily-picks-list')||$('#picks-list')||$('.picks-list'),count=$('#dailyCount');const qualified=state.picks.filter(p=>p.markets.length).length;if(count)count.textContent=state.fixtures.length?`${state.fixtures.length} verified fixtures • ${qualified} qualifying picks`:'No verified fixtures found';if(!host)return;if(state.error){host.innerHTML='<div class="panel"><strong>Daily Picks unavailable</strong><p>'+esc(state.error)+'</p></div>';return;}if(!state.fixtures.length){host.innerHTML='<div class="panel"><strong>No verified upcoming fixtures found</strong><p>The live providers returned no upcoming football matches for today. The system will not invent matches.</p></div>';return;}const byId=new Map(state.picks.map(p=>[p.fixture.id,p]));host.innerHTML=state.fixtures.slice(0,50).map((f,i)=>fixtureCard(f,byId.get(f.id),i)).join('');}
async function getRecentForm(api,teamId,teamName){if(teamId&&api?.recentMatchesById){const byId=await api.recentMatchesById(teamId,teamName,5);if(byId?.rows?.length)return byId;}if(teamName&&api?.recentMatches)return api.recentMatches(teamName,5);return null;}
async function load(){state.error=null;state.fixtures=[];state.picks=[];try{let r;if(window.PredictIQDataProvider?.getDailyFixtures)r=await window.PredictIQDataProvider.getDailyFixtures(todayISO());else if(window.PredictIQFreeData?.getDailyFixtures)r=await window.PredictIQFreeData.getDailyFixtures(todayISO());else throw new Error('No daily fixture provider is connected.');state.fixtures=Array.isArray(r?.fixtures)?r.fixtures:[];state.source=r?.source||'free provider';const api=window.PredictIQFreeData;if(!api?.recentMatchesById&&!api?.recentMatches)throw new Error('Recent-form lookup is not connected.');
const results=await Promise.all(state.fixtures.slice(0,50).map(async f=>{try{const [h,a]=await Promise.all([getRecentForm(api,f.homeTeamId,f.home),getRecentForm(api,f.awayTeamId,f.away)]);const p=makePick(f,h,a);if(h?.rows?.length&&a?.rows?.length)p.formMatches=Math.min(h.rows.length,a.rows.length);return p;}catch(err){return {fixture:f,markets:[],confidence:0,error:true};}}));state.picks.push(...results);
state.updatedAt=new Date().toISOString();}catch(e){state.error=e?.message||'Unable to load verified daily picks.';}render();const stamp=$('#dailyUpdated');if(stamp&&!state.error)stamp.textContent='Last verified analysis: '+new Date(state.updatedAt).toLocaleString()+' • '+(state.source||'provider');}
function scheduleRefresh(){const now=new Date(),slots=[8,14,20];let delay=0;for(const h of slots){const n=new Date(now);n.setHours(h,0,0,0);if(n>now){delay=n-now;break;}}if(!delay){const n=new Date(now);n.setDate(n.getDate()+1);n.setHours(8,0,0,0);delay=n-now;}setTimeout(async()=>{await load();scheduleRefresh();},delay);}
window.PredictIQDailyPicks={load,refresh:load,getState:()=>({...state})};document.addEventListener('DOMContentLoaded',()=>{load();scheduleRefresh();});
})();
