/* PredictIQ Daily Picks — verified fixtures + recent-form scoring. */
(function(){
  'use strict';
  const state={fixtures:[],picks:[],updatedAt:null,source:null,error:null};
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function todayISO(){const n=new Date();return new Intl.DateTimeFormat('en-CA',{timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(n);}
  function formScore(x){if(!x?.rows?.length)return null; const r=x.rows; const pts=r.reduce((s,m)=>s+(m.r==='W'?3:m.r==='D'?1:0),0)/(r.length*3); const gd=r.reduce((s,m)=>s+(m.gf-m.ga),0)/Math.max(1,r.length); return Math.max(0,Math.min(1,.55*pts+.45*(.5+gd/6)));}
  function makePick(f,h,a){const hs=formScore(h),as=formScore(a);if(hs==null||as==null)return null; const edge=hs-as; const home=Math.max(.05,Math.min(.9,.5+edge*.38+.08)); const draw=Math.max(.05,Math.min(.45,.25-Math.abs(edge)*.08)); const away=Math.max(.05,1-home-draw); const total=hs+as; const over25=Math.max(.12,Math.min(.88,.18+total*.55)); const btts=Math.max(.12,Math.min(.88,.25+(hs+as)*.42)); const markets=[{name:'Home or Draw (1X)',prob:home+draw,why:'Home side has the stronger recent-form signal.'},{name:'Away or Draw (X2)',prob:away+draw,why:'Away side has the stronger recent-form signal.'},{name:'Under 4.5 Goals',prob:1-Math.max(0.03,over25*.55),why:'Recent scoring and goal-difference signals do not support an extreme total.'},{name:'Both Teams To Score',prob:btts,why:'Recent attacking output on both sides supports a scoring scenario.'}].filter(m=>m.prob>=.80).sort((a,b)=>b.prob-a.prob).slice(0,3); return {fixture:f,markets,confidence:markets[0]?.prob||0,homeForm:hs,awayForm:as};}
  function render(){const host=$('#dailyList')||$('#daily-picks-list')||$('#picks-list')||$('.picks-list');const count=$('#dailyCount');if(count)count.textContent=state.picks.length?`${state.picks.length} qualifying daily picks`:'No qualifying picks found';if(!host)return;if(state.error){host.innerHTML='<div class="panel"><strong>Daily Picks unavailable</strong><p>'+esc(state.error)+'</p></div>';return;}if(!state.picks.length){host.innerHTML='<div class="panel"><strong>No qualifying picks yet</strong><p>Verified fixtures were found, but none met the current confidence threshold using available recent-form data. The system will not manufacture an 80% claim.</p></div>';return;}host.innerHTML=state.picks.slice(0,15).map((p,i)=>`<article class="pick-item"><div class="rank">#${i+1}</div><div><h4>${esc(p.fixture.home)} vs ${esc(p.fixture.away)}</h4><p>${esc(p.fixture.competition||'Football')} • ${esc(new Date(p.fixture.kickoff).toLocaleString())}</p>${p.markets.map(m=>`<p><strong>${esc(m.name)}</strong> — ${(m.prob*100).toFixed(1)}%<br><small>${esc(m.why)}</small></p>`).join('')}<p><span class="pick-label">MODEL QUALIFIED</span> • Recent-form sample: up to 5 matches/team</p></div></article>`).join('');}
  async function load(){state.error=null;state.fixtures=[];state.picks=[];try{let r;if(window.PredictIQDataProvider?.getDailyFixtures)r=await window.PredictIQDataProvider.getDailyFixtures(todayISO());else if(window.PredictIQFreeData?.getDailyFixtures)r=await window.PredictIQFreeData.getDailyFixtures(todayISO());else throw new Error('No daily fixture provider is connected.');state.fixtures=Array.isArray(r?.fixtures)?r.fixtures:[];state.source=r?.source||'free provider';const api=window.PredictIQFreeData;if(api?.recentMatches){for(const f of state.fixtures.slice(0,30)){const [h,a]=await Promise.all([api.recentMatches(f.home,5),api.recentMatches(f.away,5)]);const p=makePick(f,h,a);if(p?.markets?.length)state.picks.push(p);}}state.picks.sort((a,b)=>b.confidence-a.confidence);state.updatedAt=new Date().toISOString();}catch(e){state.error=e?.message||'Unable to load verified daily picks.';}render();const stamp=$('#dailyUpdated');if(stamp&&!state.error)stamp.textContent='Last verified analysis: '+new Date(state.updatedAt).toLocaleString();}
  function scheduleRefresh(){const now=new Date(),slots=[8,14,20];let delay=0;for(const h of slots){const next=new Date(now);next.setHours(h,0,0,0);if(next>now){delay=next-now;break;}}if(!delay){const next=new Date(now);next.setDate(next.getDate()+1);next.setHours(8,0,0,0);delay=next-now;}setTimeout(async()=>{await load();scheduleRefresh();},delay);}
  window.PredictIQDailyPicks={load,refresh:load,getState:()=>({...state})};document.addEventListener('DOMContentLoaded',()=>{load();scheduleRefresh();});
})();