/* PredictIQ AI — zero-cost football data layer. */
(function(){
'use strict';
const BASE='https://www.thesportsdb.com/api/v1/json/123/';
const TTL=30*60*1000,cache=new Map();
const ESPN_LEAGUES=['eng.1','eng.2','eng.3','eng.4','eng.5','esp.1','esp.2','esp.3','ger.1','ger.2','ita.1','ita.2','fra.1','fra.2','ned.1','bel.1','por.1','tur.1','sco.1','sco.2','gre.1','aut.1','sui.1','den.1','nor.1','swe.1','usa.1','mex.1','bra.1','bra.2','arg.1','col.1','ecu.1','per.1','chi.1','par.1','uru.1','jpn.1','kor.1','aus.1','chn.1','ind.1','nga.1','rsa.1','uefa.champions','uefa.europa','uefa.europa.conf','caf.champions'];
async function json(url){const hit=cache.get(url);if(hit&&Date.now()-hit.time<TTL)return hit.value;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Provider returned '+r.status);const v=await r.json();cache.set(url,{time:Date.now(),value:v});return v;}
function localDate(v){if(!v)return null;const t=Date.parse(v);if(!Number.isFinite(t))return null;const p=new Intl.DateTimeFormat('en-US',{year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(t));const y=p.find(x=>x.type==='year')?.value,m=p.find(x=>x.type==='month')?.value,d=p.find(x=>x.type==='day')?.value;return y&&m&&d?`${y}-${m}-${d}`:null;}
function kickoff(e){if(e.strTimestamp){const t=Date.parse(e.strTimestamp);if(Number.isFinite(t))return new Date(t).toISOString();}const d=String(e.dateEventLocal||e.dateEvent||'').trim(),tm=String(e.strTimeLocal||e.strTime||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(d)){const t=Date.parse(d+'T'+(tm||'12:00:00'));return Number.isFinite(t)?new Date(t).toISOString():null;}return null;}
function fixtureDate(f){const local=String(f.kickoffLocal||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(local))return local;return localDate(f.kickoff);}
function valid(f,date){if(!f?.id||!f.home||!f.away||!f.provider)return false;if(fixtureDate(f)!==date)return false;const blocked=['FT','AET','PEN','CANC','ABD','AWD','WO','PST','POSTPONED','FINAL','FINAL/OT'];if(blocked.includes(String(f.status).toUpperCase()))return false;if(f.kickoff){const t=Date.parse(f.kickoff);if(Number.isFinite(t)&&t<=Date.now())return false;}return true;}
async function sportsDbFixtures(date){const d=await json(BASE+'eventsday.php?d='+encodeURIComponent(date)+'&s=Soccer');return(Array.isArray(d.events)?d.events:[]).map(e=>({id:String(e.idEvent||''),sport:'football',competition:e.strLeague||'Football',home:e.strHomeTeam||'',away:e.strAwayTeam||'',homeTeamId:String(e.idHomeTeam||''),awayTeamId:String(e.idAwayTeam||''),kickoff:kickoff(e),kickoffLocal:e.dateEventLocal||e.dateEvent||null,timeLocal:e.strTimeLocal||e.strTime||null,status:e.strStatus||'NS',provider:'TheSportsDB'})).filter(f=>valid(f,date));}
async function espnLeagueFixtures(date,league){const ymd=date.replaceAll('-','');const d=await json('https://site.api.espn.com/apis/site/v2/sports/soccer/'+league+'/scoreboard?dates='+ymd);const out=[];for(const e of d.events||[]){const c=e.competitions?.[0],ts=c?.competitors||[],h=ts.find(x=>x.homeAway==='home'),a=ts.find(x=>x.homeAway==='away');if(!h||!a)continue;const k=e.date||c.date;const f={id:'espn-'+String(e.id),sport:'football',competition:d.leagues?.[0]?.name||league,home:h.team?.displayName||h.team?.name||'',away:a.team?.displayName||a.team?.name||'',homeTeamId:h.team?.id?'espn:all:'+h.team.id:'',awayTeamId:a.team?.id?'espn:all:'+a.team.id:'',kickoff:k||null,kickoffLocal:localDate(k),timeLocal:k?new Date(k).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):null,status:e.status?.type?.shortDetail||e.status?.type?.name||'Scheduled',provider:'ESPN'};if(valid(f,date))out.push(f);}return out;}
async function espnFixtures(date){const settled=await Promise.allSettled(ESPN_LEAGUES.map(l=>espnLeagueFixtures(date,l)));const all=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]);const seen=new Set();return all.filter(f=>{const k=f.home+'|'+f.away+'|'+f.kickoff;return !seen.has(k)&&seen.add(k);});}
async function getDailyFixtures(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||'')))throw new Error('Invalid fixture date');let a=[];try{a=await sportsDbFixtures(date);}catch(_){}if(a.length)return{fixtures:a,source:'TheSportsDB Free API',date,verified:true};const b=await espnFixtures(date);return{fixtures:b,source:b.length?'ESPN public scoreboard fallback':'No public fixture provider returned matches',date,verified:b.length>0};}
function rowsFromEspn(data,id,name,limit){const events=(data.events||[]).filter(e=>{const c=e.competitions?.[0],st=c?.status?.type?.completed||e.status?.type?.completed;return st&&c?.competitors;}).slice(-limit);const rows=[];for(const e of events){const c=e.competitions?.[0],me=c.competitors.find(x=>String(x.team?.id)===String(id));if(!me)continue;const op=c.competitors.find(x=>x!==me);const gf=Number(me.score),ga=Number(op?.score);if(!Number.isFinite(gf)||!Number.isFinite(ga))continue;rows.push({date:e.date||null,opponent:op?.team?.displayName||'',venue:me.homeAway==='home'?'H':'A',gf,ga,r:gf>ga?'W':gf===ga?'D':'L'});}return rows.length?{team:name||'',rows,win:rows.filter(r=>r.r==='W').length,draw:rows.filter(r=>r.r==='D').length,loss:rows.filter(r=>r.r==='L').length,provider:'ESPN public team schedule',complete:rows.length>=5}:null;}
async function recentMatchesById(teamId,teamName='',limit=5){const id=String(teamId||'').trim();if(!id)return null;if(id.startsWith('espn:all:')){try{const d=await json('https://site.api.espn.com/apis/site/v2/sports/soccer/all/teams/'+encodeURIComponent(id.slice(9))+'/schedule');return rowsFromEspn(d,id.slice(9),teamName,limit);}catch(_){return null;}}try{const d=await json(BASE+'eventslast.php?id='+encodeURIComponent(id));const es=(d.results||[]).filter(e=>e&&e.intHomeScore!==null&&e.intAwayScore!==null&&Number.isFinite(Number(e.intHomeScore))&&Number.isFinite(Number(e.intAwayScore))).slice(0,limit);if(!es.length)return null;const rows=es.map(e=>{const home=String(e.idHomeTeam)===id,gf=Number(home?e.intHomeScore:e.intAwayScore),ga=Number(home?e.intAwayScore:e.intHomeScore);return{date:e.dateEvent||e.strTimestamp||null,opponent:home?e.strAwayTeam:e.strHomeTeam,venue:home?'H':'A',gf,ga,r:gf>ga?'W':gf===ga?'D':'L'};});return{team:teamName||'',rows,win:rows.filter(r=>r.r==='W').length,draw:rows.filter(r=>r.r==='D').length,loss:rows.filter(r=>r.r==='L').length,provider:'TheSportsDB Free API',complete:rows.length>=5};}catch(_){return null;}}
async function recentMatches(teamName,limit=5){const q=String(teamName||'').trim();if(!q)return null;try{const s=await json(BASE+'searchteams.php?t='+encodeURIComponent(q)),ts=Array.isArray(s.teams)?s.teams:[];if(!ts.length)return null;const w=q.toLowerCase(),t=ts.slice().sort((a,b)=>(String(a.strTeam||'').toLowerCase()===w?-1:0)-(String(b.strTeam||'').toLowerCase()===w?-1:0))[0];return t?.idTeam?recentMatchesById(t.idTeam,t.strTeam||q,limit):null;}catch(_){return null;}}
window.PredictIQFreeData={provider:'TheSportsDB Free API + ESPN team-schedule fallback',free:true,cacheMinutes:30,recentMatches,recentMatchesById,getDailyFixtures,clearCache:()=>cache.clear()};
})();
