const S={odds:[],text:'',home:'',away:''};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
$('dropzone').addEventListener('dragover',e=>{e.preventDefault();$('dropzone').classList.add('drag');});
$('dropzone').addEventListener('dragleave',()=>$('dropzone').classList.remove('drag'));
$('dropzone').addEventListener('drop',e=>{e.preventDefault();$('dropzone').classList.remove('drag');readImages([...e.dataTransfer.files]);});
$('fileInput').addEventListener('change',e=>readImages([...e.target.files]));
function preprocessImage(file,scale=2.2){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const c=document.createElement('canvas'),w=Math.max(1200,Math.round(img.naturalWidth*scale)),h=Math.max(1600,Math.round(img.naturalHeight*scale));c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,w,h);const d=x.getImageData(0,0,w,h);for(let i=0;i<d.data.length;i+=4){const g=.299*d.data[i]+.587*d.data[i+1]+.114*d.data[i+2];const v=g>150?255:g<80?0:Math.round((g-80)*255/70);d.data[i]=d.data[i+1]=d.data[i+2]=v;}x.putImageData(d,0,0);URL.revokeObjectURL(url);c.toBlob(b=>b?resolve(b):reject(new Error('Image preparation failed')),'image/png');};img.onerror=reject;img.src=url;});}
async function readImages(files){const imgs=files.filter(f=>f.type.startsWith('image/'));if(!imgs.length)return;$('uploadList').innerHTML=imgs.map(f=>`<div class="upload-item"><span>${esc(f.name)}</span><span>${Math.round(f.size/1024)} KB</span></div>`).join('');let text='';$('ocrStatus').textContent='Preparing screenshots…';let worker;try{worker=await Tesseract.createWorker('eng');await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1',user_defined_dpi:'300'});for(const f of imgs){$('ocrStatus').textContent=`Reading ${f.name}…`;try{const p=await preprocessImage(f),r=await worker.recognize(p,{}, {blocks:true});text+=`\n${r.data.text||''}`;if(r.data.blocks)text+='\n'+r.data.blocks.map(b=>b.text||'').join('\n');}catch(e){console.warn('OCR failed',e);}}}finally{if(worker)await worker.terminate();}S.text=text;detectTeams(text);const parsed=window.PredictIQSportyParser?.parse(text);S.odds=parsed?.rows||[];renderOdds();$('ocrStatus').textContent=S.home&&S.away?`Detected ${S.home} vs ${S.away}. Please confirm the names.`:'OCR finished. Please enter or correct the team names.';}
function detectTeams(text){const lines=text.split(/\r?\n/).map(clean).filter(Boolean),ignore=/^(markets?|stats?|codes?|all|main|goals?|corners?|half|players?|teams?|match|over|under|asian|double chance|handicap|early goals?|1st goal|details|live|new|home|away|draw|yes|no|booking|combo|minutes?)$/i;for(const x of lines){const m=x.match(/^(.{2,40})\s+(?:vs\.?|v\.?|[-–—])\s+(.{2,40})$/i);if(m&&!ignore.test(m[1])&&!ignore.test(m[2])){S.home=clean(m[1]);S.away=clean(m[2]);break;}}if(!S.home||!S.away){const c=lines.filter(x=>x.length>=3&&x.length<=32&&!ignore.test(x)&&!/^\d/.test(x));if(c.length>=2){S.home=S.home||c[0];S.away=S.away||c[1];}}if(S.home)$('homeTeam').value=S.home;if(S.away)$('awayTeam').value=S.away;}
function renderOdds(){if(!S.odds.length){$('oddsTableWrap').innerHTML='<div class="empty-state">No readable markets yet. Upload a clearer screenshot or use the demo.</div>';return;}$('oddsTableWrap').innerHTML=`<table class="odds-table"><thead><tr><th>Market</th><th>Selection</th><th>Line</th><th>Odds</th></tr></thead><tbody>${S.odds.map((o,i)=>`<tr><td>${esc(o.market)}</td><td>${esc(o.sel)}</td><td>${o.line??'—'}</td><td><input class="odd-input" data-i="${i}" value="${Number(o.odd).toFixed(2)}" type="number" min="1.001" max="100" step="0.01"></td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('.odd-input').forEach(x=>x.onchange=e=>{const v=Number(e.target.value);if(v>=1.001&&v<=100)S.odds[Number(e.target.dataset.i)].odd=v;});}
function demo(){S.home='Copenhagen';S.away='Opponent';$('homeTeam').value=S.home;$('awayTeam').value=S.away;$('competition').value='Sample fixture';S.odds=[{market:'1X2',sel:'Home',odd:1.95},{market:'1X2',sel:'Draw',odd:3.60},{market:'1X2',sel:'Away',odd:3.80},...([.5,1.5,2.5,3.5,4.5,5.5].flatMap((line,i)=>[{market:'Over/Under',line,sel:'Over',odd:[1.02,1.15,1.50,2.25,3.75,6.70][i]},{market:'Over/Under',line,sel:'Under',odd:[12.5,5.20,2.55,1.64,1.26,1.10][i]})),{market:'BTTS',sel:'Yes',odd:1.72},{market:'BTTS',sel:'No',odd:2.05},{market:'Double Chance',sel:'1X',odd:1.30},{market:'Double Chance',sel:'12',odd:1.28},{market:'Double Chance',sel:'X2',odd:1.65}];renderOdds();$('ocrStatus').textContent='Demo odds loaded. Replace them with your screenshot.';}
$('demoBtn').onclick=demo;$('clearOddsBtn').onclick=()=>{S.odds=[];renderOdds();};
async function getForm(team){try{return window.PredictIQFreeData?.recentMatches?await window.PredictIQFreeData.recentMatches(team,5):null;}catch(e){console.warn('Free data lookup failed',e);return null;}}
function formatPick(x){return `${x.market} — ${x.sel}${x.line!=null?' '+x.line:''}`;}
function renderReport(h,a,r){$('results').classList.remove('hidden');$('resultMatch').textContent=`${h.team} vs ${a.team}`;$('resultCompetition').textContent=$('competition').value||'Match analysis';$('resultDate').textContent=$('matchDate').value||'';$('homeXg').textContent=r.xg.home.toFixed(2);$('awayXg').textContent=r.xg.away.toFixed(2);$('totalXg').textContent=r.xg.total.toFixed(2);$('matchProbabilities').innerHTML=[['Home',r.p.home],['Draw',r.p.draw],['Away',r.p.away]].map(([n,p])=>`<div class="prob-line"><span>${n}</span><div class="prob-bar"><i style="width:${p*100}%"></i></div><strong>${(p*100).toFixed(1)}%</strong></div>`).join('');$('formCards').innerHTML=[r.home,r.away].map(f=>`<div class="form-card"><h4>${esc(f.team)}</h4><div class="metrics"><div class="metric"><span>Attack</span><b>${f.attack.toFixed(0)}/100</b></div><div class="metric"><span>Defence</span><b>${f.defence.toFixed(0)}/100</b></div><div class="metric"><span>Form</span><b>${f.form.toFixed(0)}/100</b></div><div class="metric"><span>Last 5</span><b>${f.win??0}W ${f.draw??0}D ${f.loss??0}L</b></div></div></div>`).join('');const top=r.top3[0];$('noBetBox').classList.toggle('hidden',!!top);if(top){$('topPickMarket').textContent=formatPick(top);$('topPickProb').textContent=(top.probability*100).toFixed(1)+'%';$('topPickOdds').textContent=top.odd.toFixed(2);$('topPickImplied').textContent=(top.implied*100).toFixed(1)+'%';$('topPickEdge').textContent=`${top.edge>=0?'+':''}${(top.edge*100).toFixed(1)} pp`;$('topPickConfidence').textContent=top.confidence>=85&&top.probability>=.85?'HIGH':top.confidence>=60?'MEDIUM':'DATA LIMITED';$('topPickReason').textContent=`Model ${(top.probability*100).toFixed(1)}% vs bookmaker implied ${(top.implied*100).toFixed(1)}%. Data confidence ${top.confidence}%.`;}else{$('topPickMarket').textContent='No qualifying market';$('topPickProb').textContent='—';$('topPickOdds').textContent='—';$('topPickImplied').textContent='—';$('topPickEdge').textContent='—';$('topPickConfidence').textContent='NO BET';$('topPickReason').textContent='Not enough evidence met the model filters.';}$('topThree').innerHTML=r.top3.map((x,i)=>`<div class="pick-item"><div class="rank">#${i+1}</div><div><h4>${esc(formatPick(x))}</h4><p>Odds ${x.odd.toFixed(2)} • model ${(x.probability*100).toFixed(1)}% • implied ${(x.implied*100).toFixed(1)}% • edge ${(x.edge*100).toFixed(1)} pp</p></div><div class="prob">${(x.probability*100).toFixed(1)}%</div></div>`).join('')||'<div class="empty-state">No qualifying selections.</div>';$('modelNotes').innerHTML=[`Last five matches are weighted by recency.`,`Expected goals: ${r.xg.home.toFixed(2)} home / ${r.xg.away.toFixed(2)} away.`,`Data confidence: ${r.dataConfidence}%.`,`Bookmaker odds are used for comparison, not copied as predictions.`].map(x=>`<li>${x}</li>`).join('');$('results').scrollIntoView({behavior:'smooth'});}
$('analyzeBtn').onclick=async()=>{const home=$('homeTeam').value.trim(),away=$('awayTeam').value.trim();if(!home||!away){alert('Please confirm both team names.');return;}if(!S.odds.length){alert('Please upload an odds screenshot first.');return;}$('analyzeBtn').disabled=true;$('analyzeBtn').textContent='Analyzing…';try{const[h,a]=await Promise.all([getForm(home),getForm(away)]);if(!h||!a||h.rows.length<5||a.rows.length<5){$('results').classList.remove('hidden');$('noBetBox').classList.remove('hidden');$('topPickMarket').textContent='No prediction — insufficient verified data';$('topPickProb').textContent='—';$('topPickConfidence').textContent='NO BET';$('topPickReason').textContent='The free source did not provide five verified recent matches for both teams.';$('topThree').innerHTML='<div class="empty-state">No prediction generated. The system will not invent missing statistics.</div>';return;}const r=window.PredictIQEngine.analyze(S.odds,h,a);renderReport(h,a,r);}catch(e){console.error(e);alert('Analysis failed because verified data or the model was unavailable. No fabricated prediction was produced.');}finally{$('analyzeBtn').disabled=false;$('analyzeBtn').textContent='Analyze match';}};
