/* PredictIQ AI — evidence/research layer
 * Converts model signals into an auditable match explanation.
 * It never changes model probabilities; it only explains them and highlights risk.
 */
(function(){'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(r){const results=$('results');if(!results)return;let box=$('researchEvidence');if(!box){box=document.createElement('div');box.id='researchEvidence';box.className='panel';results.appendChild(box);}const factors=(r.factors||[]).map(f=>{const d=f.home-f.away,lead=d>0?r.home.team:d<0?r.away.team:'Even';return `<div class="evidence-row"><div><strong>${esc(f.label)}</strong><span>${esc(lead)}</span></div><div class="evidence-score"><b>${Number(f.home).toFixed(0)}</b><i>vs</i><b>${Number(f.away).toFixed(0)}</b></div></div>`}).join('');const risks=[];if(r.dataConfidence<100)risks.push('The public data sample is incomplete; confidence is reduced.');if(Math.abs(r.p.home-r.p.away)<.10)risks.push('The two sides are close in the win probabilities, so the match has elevated variance.');if(r.p.draw>.28)risks.push('Draw probability is relatively high; a narrow margin separates the teams.');if(Math.abs(r.xg.home-r.xg.away)<.25)risks.push('Expected goals are close, making the result harder to separate.');if(!risks.length)risks.push('No major statistical warning was detected from the available pre-match data.');box.innerHTML=`<div class="panel-head"><div><div class="step-label">RESEARCH & EVIDENCE</div><h3>Why the model predicts this</h3></div><span class="muted">Evidence only — probabilities remain statistical outputs</span></div><div class="evidence-grid"><div><h4>Key factors</h4><div class="evidence-list">${factors}</div></div><div><h4>Model reasoning</h4><ul class="notes">${(r.reasons||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div><div class="research-risk"><h4>What could make the prediction wrong?</h4><ul class="notes">${risks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="method-line"><strong>Engine stack:</strong> ${esc(r.method||'Statistical ensemble')} • <strong>Data coverage:</strong> ${r.dataConfidence}%</div>`;}
const style=document.createElement('style');style.textContent=`.evidence-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.evidence-list{display:grid;gap:8px}.evidence-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 12px;border:1px solid rgba(255,255,255,.08);border-radius:10px}.evidence-row div:first-child{display:grid;gap:3px}.evidence-row span{font-size:12px;opacity:.7}.evidence-score{display:flex;gap:7px;align-items:center}.evidence-score i{font-size:11px;opacity:.5}.research-risk{margin-top:20px;padding-top:18px;border-top:1px solid rgba(255,255,255,.08)}.method-line{margin-top:16px;font-size:12px;opacity:.72}@media(max-width:700px){.evidence-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);window.PredictIQResearch={render};})();
